In [1]:
import pandas as pd

In [2]:
raw_df = pd.read_csv("data_10000000.csv").head(3000000)

In [3]:
%%timeit -n1 -r10
print(raw_df.groupby("country_of_birth").count())

                   user_id   name  date_of_birth  email  record_year  score
country_of_birth
Afghanistan          12087  12087          12087  12087        12087  12087
Albania              12360  12360          12360  12360        12360  12360
Algeria              12196  12196          12196  12196        12196  12196
American Samoa       12173  12173          12173  12173        12173  12173
Andorra              12200  12200          12200  12200        12200  12200
...                    ...    ...            ...    ...          ...    ...
Wallis and Futuna    12226  12226          12226  12226        12226  12226
Western Sahara       12152  12152          12152  12152        12152  12152
Yemen                12153  12153          12153  12153        12153  12153
Zambia               12112  12112          12112  12112        12112  12112
Zimbabwe             12436  12436          12436  12436        12436  12436

[243 rows x 6 columns]
                   user_id   name  date_of_birth  email  record_year  score
country_of_birth
Afghanistan          12087  12087          12087  12087        12087  12087
Albania              12360  12360          12360  12360        12360  12360
Algeria              12196  12196          12196  12196        12196  12196
American Samoa       12173  12173          12173  12173        12173  12173
Andorra              12200  12200          12200  12200        12200  12200
...                    ...    ...            ...    ...          ...    ...
Wallis and Futuna    12226  12226          12226  12226        12226  12226
Western Sahara       12152  12152          12152  12152        12152  12152
Yemen                12153  12153          12153  12153        12153  12153
Zambia               12112  12112          12112  12112        12112  12112
Zimbabwe             12436  12436          12436  12436        12436  12436

[243 rows x 6 columns]
                   user_id   name  date_of_birth  email  record_year  score
country_of_birth
Afghanistan          12087  12087          12087  12087        12087  12087
Albania              12360  12360          12360  12360        12360  12360
Algeria              12196  12196          12196  12196        12196  12196
American Samoa       12173  12173          12173  12173        12173  12173
Andorra              12200  12200          12200  12200        12200  12200
...                    ...    ...            ...    ...          ...    ...
Wallis and Futuna    12226  12226          12226  12226        12226  12226
Western Sahara       12152  12152          12152  12152        12152  12152
Yemen                12153  12153          12153  12153        12153  12153
Zambia               12112  12112          12112  12112        12112  12112
Zimbabwe             12436  12436          12436  12436        12436  12436

[243 rows x 6 columns]
                   user_id   name  date_of_birth  email  record_year  score
country_of_birth
Afghanistan          12087  12087          12087  12087        12087  12087
Albania              12360  12360          12360  12360        12360  12360
Algeria              12196  12196          12196  12196        12196  12196
American Samoa       12173  12173          12173  12173        12173  12173
Andorra              12200  12200          12200  12200        12200  12200
...                    ...    ...            ...    ...          ...    ...
Wallis and Futuna    12226  12226          12226  12226        12226  12226
Western Sahara       12152  12152          12152  12152        12152  12152
Yemen                12153  12153          12153  12153        12153  12153
Zambia               12112  12112          12112  12112        12112  12112
Zimbabwe             12436  12436          12436  12436        12436  12436

[243 rows x 6 columns]
                   user_id   name  date_of_birth  email  record_year  score
country_of_birth
Afghanistan          12087  12087          12087  12087        12087  12087
Albania              12360  12360          12360  12360        12360  12360
Algeria              12196  12196          12196  12196        12196  12196
American Samoa       12173  12173          12173  12173        12173  12173
Andorra              12200  12200          12200  12200        12200  12200
...                    ...    ...            ...    ...          ...    ...
Wallis and Futuna    12226  12226          12226  12226        12226  12226
Western Sahara       12152  12152          12152  12152        12152  12152
Yemen                12153  12153          12153  12153        12153  12153
Zambia               12112  12112          12112  12112        12112  12112
Zimbabwe             12436  12436          12436  12436        12436  12436

[243 rows x 6 columns]
                   user_id   name  date_of_birth  email  record_year  score
country_of_birth
Afghanistan          12087  12087          12087  12087        12087  12087
Albania              12360  12360          12360  12360        12360  12360
Algeria              12196  12196          12196  12196        12196  12196
American Samoa       12173  12173          12173  12173        12173  12173
Andorra              12200  12200          12200  12200        12200  12200
...                    ...    ...            ...    ...          ...    ...
Wallis and Futuna    12226  12226          12226  12226        12226  12226
Western Sahara       12152  12152          12152  12152        12152  12152
Yemen                12153  12153          12153  12153        12153  12153
Zambia               12112  12112          12112  12112        12112  12112
Zimbabwe             12436  12436          12436  12436        12436  12436

[243 rows x 6 columns]
                   user_id   name  date_of_birth  email  record_year  score
country_of_birth
Afghanistan          12087  12087          12087  12087        12087  12087
Albania              12360  12360          12360  12360        12360  12360
Algeria              12196  12196          12196  12196        12196  12196
American Samoa       12173  12173          12173  12173        12173  12173
Andorra              12200  12200          12200  12200        12200  12200
...                    ...    ...            ...    ...          ...    ...
Wallis and Futuna    12226  12226          12226  12226        12226  12226
Western Sahara       12152  12152          12152  12152        12152  12152
Yemen                12153  12153          12153  12153        12153  12153
Zambia               12112  12112          12112  12112        12112  12112
Zimbabwe             12436  12436          12436  12436        12436  12436

[243 rows x 6 columns]
                   user_id   name  date_of_birth  email  record_year  score
country_of_birth
Afghanistan          12087  12087          12087  12087        12087  12087
Albania              12360  12360          12360  12360        12360  12360
Algeria              12196  12196          12196  12196        12196  12196
American Samoa       12173  12173          12173  12173        12173  12173
Andorra              12200  12200          12200  12200        12200  12200
...                    ...    ...            ...    ...          ...    ...
Wallis and Futuna    12226  12226          12226  12226        12226  12226
Western Sahara       12152  12152          12152  12152        12152  12152
Yemen                12153  12153          12153  12153        12153  12153
Zambia               12112  12112          12112  12112        12112  12112
Zimbabwe             12436  12436          12436  12436        12436  12436

[243 rows x 6 columns]
                   user_id   name  date_of_birth  email  record_year  score
country_of_birth
Afghanistan          12087  12087          12087  12087        12087  12087
Albania              12360  12360          12360  12360        12360  12360
Algeria              12196  12196          12196  12196        12196  12196
American Samoa       12173  12173          12173  12173        12173  12173
Andorra              12200  12200          12200  12200        12200  12200
...                    ...    ...            ...    ...          ...    ...
Wallis and Futuna    12226  12226          12226  12226        12226  12226
Western Sahara       12152  12152          12152  12152        12152  12152
Yemen                12153  12153          12153  12153        12153  12153
Zambia               12112  12112          12112  12112        12112  12112
Zimbabwe             12436  12436          12436  12436        12436  12436

[243 rows x 6 columns]
                   user_id   name  date_of_birth  email  record_year  score
country_of_birth
Afghanistan          12087  12087          12087  12087        12087  12087
Albania              12360  12360          12360  12360        12360  12360
Algeria              12196  12196          12196  12196        12196  12196
American Samoa       12173  12173          12173  12173        12173  12173
Andorra              12200  12200          12200  12200        12200  12200
...                    ...    ...            ...    ...          ...    ...
Wallis and Futuna    12226  12226          12226  12226        12226  12226
Western Sahara       12152  12152          12152  12152        12152  12152
Yemen                12153  12153          12153  12153        12153  12153
Zambia               12112  12112          12112  12112        12112  12112
Zimbabwe             12436  12436          12436  12436        12436  12436

[243 rows x 6 columns]
1.06 s ± 27.2 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)

In [4]:
%%timeit -n1 -r10

joined_df = raw_df.merge(raw_df, on=['country_of_birth', 'date_of_birth'], how='inner')
diff_df = joined_df[joined_df['user_id_x'] != joined_df['user_id_y']]
diff_df['diff'] = abs(diff_df['score_x']-diff_df['score_y'])
diff_df.groupby('country_of_birth').mean().sort_values(by='diff', ascending=False)

<magic-timeit>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<magic-timeit>:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
<magic-timeit>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<magic-timeit>:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
<magic-timeit>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<magic-timeit>:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
<magic-timeit>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<magic-timeit>:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
<magic-timeit>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<magic-timeit>:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
<magic-timeit>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<magic-timeit>:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
<magic-timeit>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<magic-timeit>:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
<magic-timeit>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<magic-timeit>:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
<magic-timeit>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<magic-timeit>:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
<magic-timeit>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<magic-timeit>:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.

6 s ± 120 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)